### ISSUE TITLE
1.9 fails to open

### ISSUE THREAD

**Issue by martinhale** [wildfoundry/dataplicity-porthole-releases-osx#14] opened 2019-06-27 08:02 UTC
Hey,

Version 1.9 fails to open for me. Gives an error saying the application is damaged.

Any ideas?

**Comment by Radoslaw-K** [comment] 2019-06-27 10:06
Hey @martinhale ,

Thank you for letting us know. The issue is now fixed. The fix is implemented in the same version so all you need to do is to download again the app.

Best,
Radoslav

**Closed as completed by Radoslaw-K** 2019-06-27 10:06 UTC
